<a href="https://colab.research.google.com/github/keerthireddy17/Pyspark-Project/blob/main/FBIDataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import pandas as pd
import numpy as np
import datetime as dt

In [46]:
from google.colab import drive
drive.mount('/content/fbi.xlsx')

Drive already mounted at /content/fbi.xlsx; to attempt to forcibly remount, call drive.mount("/content/fbi.xlsx", force_remount=True).

In [47]:
# pd.read_excel()

fbi = pd.read_excel('/fbi.xlsx')
fbi.head()

,Table 2,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,Crime in the United States1,NaN,NaN,NaN,,,,,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"by Region, Geographic Division, and State, 201...",NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Area,Year,Population2,Violent crime3,NaN,Murder and \nnonnegligent \nmanslaughter,NaN,Rape\n(revised definition)4,NaN,Rape\n(legacy definition)5,NaN,Robbery,NaN,Aggravated assault,NaN,Property crime,NaN,Burglary,NaN,Larceny-theft,NaN,Motor vehicle theft,NaN
3,NaN,NaN,NaN,,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000"
4,"United States Total6, 7, 8, 9",2015,320896618,1234183,384.6,15883,4.9,126134,39.3,91261,28.4,328109,102.2,764057,238.1,8024115,2500.5,1587564,494.7,5723488,1783.6,713063,222.2

In [48]:
pd.set_option('display.max.columns', None)
fbi.head()

,Table 2,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,Crime in the United States1,NaN,NaN,NaN,,,,,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"by Region, Geographic Division, and State, 201...",NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Area,Year,Population2,Violent crime3,NaN,Murder and \nnonnegligent \nmanslaughter,NaN,Rape\n(revised definition)4,NaN,Rape\n(legacy definition)5,NaN,Robbery,NaN,Aggravated assault,NaN,Property crime,NaN,Burglary,NaN,Larceny-theft,NaN,Motor vehicle theft,NaN
3,NaN,NaN,NaN,,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000"
4,"United States Total6, 7, 8, 9",2015,320896618,1234183,384.6,15883,4.9,126134,39.3,91261,28.4,328109,102.2,764057,238.1,8024115,2500.5,1587564,494.7,5723488,1783.6,713063,222.2

In [49]:
# The first 2 rows and the last 8 rows are trash, clean it!
fbi.drop(fbi.index[0:2], inplace=True)
fbi.drop(fbi.index[-11:], inplace=True)
fbi.reset_index(inplace=True, drop=True)
fbi.head()

,Table 2,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,Area,Year,Population2,Violent crime3,NaN,Murder and \nnonnegligent \nmanslaughter,NaN,Rape\n(revised definition)4,NaN,Rape\n(legacy definition)5,NaN,Robbery,NaN,Aggravated assault,NaN,Property crime,NaN,Burglary,NaN,Larceny-theft,NaN,Motor vehicle theft,NaN
1,NaN,NaN,NaN,,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000",,"Rate per \n100,000"
2,"United States Total6, 7, 8, 9",2015,320896618,1234183,384.6,15883,4.9,126134,39.3,91261,28.4,328109,102.2,764057,238.1,8024115,2500.5,1587564,494.7,5723488,1783.6,713063,222.2
3,NaN,2016,323127513,1283058,397.1,17250,5.3,130603,40.4,95730,29.6,332198,102.8,803007,248.5,7919035,2450.7,1515096,468.9,5638455,1745,765484,236.9
4,NaN,Percent change,NaN,4,3.2,8.6,7.9,3.5,2.8,4.9,4.2,1.2,0.5,5.1,4.4,-1.3,-2,-4.6,-5.2,-1.5,-2.2,7.4,6.6

In [50]:
fbi.iloc[0]

Table 2                                            Area
Unnamed: 1                                         Year
Unnamed: 2                                  Population2
Unnamed: 3                               Violent crime3
Unnamed: 4                                          NaN
Unnamed: 5     Murder and \nnonnegligent \nmanslaughter
Unnamed: 6                                          NaN
Unnamed: 7                  Rape\n(revised definition)4
Unnamed: 8                                          NaN
Unnamed: 9                   Rape\n(legacy definition)5
Unnamed: 10                                         NaN
Unnamed: 11                                     Robbery
Unnamed: 12                                         NaN
Unnamed: 13                          Aggravated assault
Unnamed: 14                                         NaN
Unnamed: 15                              Property crime
Unnamed: 16                                         NaN
Unnamed: 17                                    Burglary
Unnamed: 18                                         NaN
Unnamed: 19                               Larceny-theft
Unnamed: 20                                         NaN
Unnamed: 21                         Motor vehicle theft
Unnamed: 22                                         NaN
Name: 0, dtype: object

In [51]:
cols = []

for i in range(0, 4):
    cols.append(fbi.iloc[0][i])

for i in range(4,23):
    if i%2 == 1:
        cols.append(fbi.iloc[0][i])

cols

['Area',
 'Year',
 'Population2',
 'Violent crime3',
 'Murder and \nnonnegligent \nmanslaughter',
 'Rape\n(revised definition)4',
 'Rape\n(legacy definition)5',
 'Robbery',
 'Aggravated assault',
 'Property crime',
 'Burglary',
 'Larceny-theft',
 'Motor vehicle theft']

In [52]:
# Update column names

fbi.columns = fbi.iloc[0]
fbi.drop(fbi.index[0:2], inplace=True)
fbi.reset_index(inplace=True, drop=True)
fbi.head()

,Area,Year,Population2,Violent crime3,NaN,Murder and \nnonnegligent \nmanslaughter,NaN,Rape\n(revised definition)4,NaN,Rape\n(legacy definition)5,NaN,Robbery,NaN,Aggravated assault,NaN,Property crime,NaN,Burglary,NaN,Larceny-theft,NaN,Motor vehicle theft,NaN
0,"United States Total6, 7, 8, 9",2015,320896618,1234183,384.6,15883,4.9,126134,39.3,91261,28.4,328109,102.2,764057,238.1,8024115,2500.5,1587564,494.7,5723488,1783.6,713063,222.2
1,NaN,2016,323127513,1283058,397.1,17250,5.3,130603,40.4,95730,29.6,332198,102.8,803007,248.5,7919035,2450.7,1515096,468.9,5638455,1745,765484,236.9
2,NaN,Percent change,NaN,4,3.2,8.6,7.9,3.5,2.8,4.9,4.2,1.2,0.5,5.1,4.4,-1.3,-2,-4.6,-5.2,-1.5,-2.2,7.4,6.6
3,Northeast6,2015,56184737,180474,321.2,1967,3.5,16415,29.2,11912,21.2,56202,100,105890,188.5,951940,1694.3,157910,281.1,737087,1311.9,56943,101.3
4,NaN,2016,56209510,178244,317.1,1955,3.5,16651,29.6,12219,21.7,53033,94.3,106605,189.7,909897,1618.8,142720,253.9,709721,1262.6,57456,102.2

In [53]:
cols = fbi.columns[fbi.columns.notnull()]
fbi = fbi[cols].copy()
fbi.head()

,Area,Year,Population2,Violent crime3,Murder and \nnonnegligent \nmanslaughter,Rape\n(revised definition)4,Rape\n(legacy definition)5,Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft
0,"United States Total6, 7, 8, 9",2015,320896618,1234183,15883,126134,91261,328109,764057,8024115,1587564,5723488,713063
1,NaN,2016,323127513,1283058,17250,130603,95730,332198,803007,7919035,1515096,5638455,765484
2,NaN,Percent change,NaN,4,8.6,3.5,4.9,1.2,5.1,-1.3,-4.6,-1.5,7.4
3,Northeast6,2015,56184737,180474,1967,16415,11912,56202,105890,951940,157910,737087,56943
4,NaN,2016,56209510,178244,1955,16651,12219,53033,106605,909897,142720,709721,57456

In [54]:
# Remove Percent Change rows

for index, row in fbi.iterrows():
    if row['Year'] == 'Percent change':
        fbi.drop(index, inplace=True)
fbi.reset_index(inplace=True, drop=True)
fbi.head()

,Area,Year,Population2,Violent crime3,Murder and \nnonnegligent \nmanslaughter,Rape\n(revised definition)4,Rape\n(legacy definition)5,Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft
0,"United States Total6, 7, 8, 9",2015,320896618,1234183,15883,126134,91261,328109,764057,8024115,1587564,5723488,713063
1,NaN,2016,323127513,1283058,17250,130603,95730,332198,803007,7919035,1515096,5638455,765484
2,Northeast6,2015,56184737,180474,1967,16415,11912,56202,105890,951940,157910,737087,56943
3,NaN,2016,56209510,178244,1955,16651,12219,53033,106605,909897,142720,709721,57456
4,New England6,2015,14710229,42121,326,4602,3374,9629,27564,257073,46260,193051,17762

In [55]:
# The first 2 rows are not necessary, clean it!

fbi.drop(fbi.index[0:2], inplace=True)
fbi.reset_index(inplace=True, drop=True)
fbi.head()

,Area,Year,Population2,Violent crime3,Murder and \nnonnegligent \nmanslaughter,Rape\n(revised definition)4,Rape\n(legacy definition)5,Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft
0,Northeast6,2015,56184737,180474,1967,16415,11912,56202,105890,951940,157910,737087,56943
1,NaN,2016,56209510,178244,1955,16651,12219,53033,106605,909897,142720,709721,57456
2,New England6,2015,14710229,42121,326,4602,3374,9629,27564,257073,46260,193051,17762
3,NaN,2016,14735525,41598,292,4505,3328,9407,27394,243769,42095,182985,18689
4,Connecticut,2015,3584730,7938,116,798,585,2925,4099,65610,10286,48898,6426

In [57]:
# Fill the blanks in Area column

for i in range(fbi.shape[0]):
    if str(fbi['Area'][i]) == 'nan':
        fbi['Area'][i] = fbi['Area'][i-1]

fbi.head(20)

,Area,Year,Population2,Violent crime3,Murder and \nnonnegligent \nmanslaughter,Rape\n(revised definition)4,Rape\n(legacy definition)5,Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft
0,Northeast6,2015,56184737,180474,1967,16415,11912,56202,105890,951940,157910,737087,56943
1,Northeast6,2016,56209510,178244,1955,16651,12219,53033,106605,909897,142720,709721,57456
2,New England6,2015,14710229,42121,326,4602,3374,9629,27564,257073,46260,193051,17762
3,New England6,2016,14735525,41598,292,4505,3328,9407,27394,243769,42095,182985,18689
4,Connecticut,2015,3584730,7938,116,798,585,2925,4099,65610,10286,48898,6426
5,Connecticut,2016,3576452,8123,78,763,561,2703,4579,64664,10045,47512,7107
6,Maine,2015,1329453,1726,23,461,337,311,931,24361,4694,18853,814
7,Maine,2016,1331479,1648,20,412,300,266,950,21912,4003,17134,775
8,Massachusetts,2015,6784240,26453,131,2082,1538,5266,18974,114547,21826,84676,8045
9,Massachusetts,2016,6811779,25677,134,2128,1592,5365,18050,106339,19193,79088,8058
10,New Hampshire,2015,1330111,2692,15,644,468,475,1558,23453,3482,19076,895
11,New Hampshire,2016,1334795,2637,17,582,423,427,1611,20194,2963,16360,871
12,Rhode Island6,2015,1055607,2565,31,467,342,547,1520,20038,3938,14714,1386
13,Rhode Island6,2016,1056426,2524,29,442,328,540,1513,20058,3788,14674,1596
14,Vermont,2015,626088,747,10,150,104,105,482,9064,2034,6834,196
15,Vermont,2016,624594,989,14,178,124,106,691,10602,2103,8217,282
16,Middle Atlantic6,2015,41474508,138353,1641,11813,8538,46573,78326,694867,111650,544036,39181
17,Middle Atlantic6,2016,41473985,136646,1663,12146,8891,43626,79211,666128,100625,526736,38767
18,New Jersey,2015,8935421,22879,363,1373,1019,9729,11414,145701,27960,105963,11778
19,New Jersey,2016,8944469,21914,372,1453,1089,8984,11105,138152,25284,101540,11328

In [58]:
# Look at this here! If any row has '5' space, then the row must be State!

for i in fbi['Area'].unique():
    print(i)

Northeast6
New England6
     Connecticut
     Maine
     Massachusetts
     New Hampshire
     Rhode Island6
     Vermont
Middle Atlantic6
     New Jersey
     New York6
     Pennsylvania
Midwest6
East North Central6
     Illinois
     Indiana6
     Michigan
     Ohio6
     Wisconsin6
West North Central6
     Iowa
     Kansas
     Minnesota
     Missouri
     Nebraska6
     North Dakota
     South Dakota6
South6, 7 ,8
South Atlantic6, 7, 8
     Delaware
     District of Columbia7
     Florida
     Georgia8
     Maryland
     North Carolina6
     South Carolina
     Virginia
     West Virginia
East South Central6
     Alabama
     Kentucky
     Mississippi6
     Tennessee
West South Central6
     Arkansas
     Louisiana
     Oklahoma6
     Texas
West6
Mountain6
     Arizona
     Colorado
     Idaho
     Montana
     Nevada
     New Mexico6
     Utah
     Wyoming
Pacific6
     Alaska
     California
     Hawaii
     Oregon6
     Washington6
Puerto Rico9

In [59]:
#  Clear unnecessary numbers of States

for i in range(fbi.shape[0]):
    # Specific solution for South and South Atlantic
    if fbi['Area'][i] == 'South6, 7 ,8':
        fbi['Area'][i] = 'South'
    if fbi['Area'][i] == 'South Atlantic6, 7,8':
        fbi['Area'][i] = 'South Atlantic'
    for j in fbi['Area'][i]:
        try:
            a = int(j)
        except:
            a = None

        if isinstance(a, int):
            fbi['Area'][i] = fbi['Area'][i].replace(str(a)+', ', '')
            fbi['Area'][i] = fbi['Area'][i].replace(str(a), '')

fbi.head(10)

,Area,Year,Population2,Violent crime3,Murder and \nnonnegligent \nmanslaughter,Rape\n(revised definition)4,Rape\n(legacy definition)5,Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft
0,Northeast,2015,56184737,180474,1967,16415,11912,56202,105890,951940,157910,737087,56943
1,Northeast,2016,56209510,178244,1955,16651,12219,53033,106605,909897,142720,709721,57456
2,New England,2015,14710229,42121,326,4602,3374,9629,27564,257073,46260,193051,17762
3,New England,2016,14735525,41598,292,4505,3328,9407,27394,243769,42095,182985,18689
4,Connecticut,2015,3584730,7938,116,798,585,2925,4099,65610,10286,48898,6426
5,Connecticut,2016,3576452,8123,78,763,561,2703,4579,64664,10045,47512,7107
6,Maine,2015,1329453,1726,23,461,337,311,931,24361,4694,18853,814
7,Maine,2016,1331479,1648,20,412,300,266,950,21912,4003,17134,775
8,Massachusetts,2015,6784240,26453,131,2082,1538,5266,18974,114547,21826,84676,8045
9,Massachusetts,2016,6811779,25677,134,2128,1592,5365,18050,106339,19193,79088,8058

In [60]:
# Clear unnecessary numbers of Column names

cols = fbi.columns
new_cols = []

for i in cols:
    for j in i:
        try:
            a = int(j)

        except:
            a = None

    if isinstance(a, int):
        b = i.replace(j, '')

    else:
        b = i

    new_cols.append(b)

fbi.columns = new_cols
fbi.head()

,Area,Year,Population,Violent crime,Murder and \nnonnegligent \nmanslaughter,Rape\n(revised definition),Rape\n(legacy definition),Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft
0,Northeast,2015,56184737,180474,1967,16415,11912,56202,105890,951940,157910,737087,56943
1,Northeast,2016,56209510,178244,1955,16651,12219,53033,106605,909897,142720,709721,57456
2,New England,2015,14710229,42121,326,4602,3374,9629,27564,257073,46260,193051,17762
3,New England,2016,14735525,41598,292,4505,3328,9407,27394,243769,42095,182985,18689
4,Connecticut,2015,3584730,7938,116,798,585,2925,4099,65610,10286,48898,6426

In [61]:
# Split data by regions

north_east = fbi.loc[fbi['Area']=='Northeast'].index.values.astype(int)[0]
mid_west = fbi.loc[fbi['Area']=='Midwest'].index.values.astype(int)[0]
south = fbi.loc[fbi['Area']=='South'].index.values.astype(int)[0]
west = fbi.loc[fbi['Area']=='West'].index.values.astype(int)[0]

fbi_north = fbi[north_east:mid_west].copy()
fbi_mid = fbi[mid_west:south].copy()
fbi_south = fbi[south:west].copy()
fbi_west = fbi[west:].copy()

In [62]:
# Add 'Region' columns

fbi_north['Region'] = 'Northeast'
fbi_mid['Region'] = 'Midwest'
fbi_south['Region'] = 'South'
fbi_west['Region'] = 'West'

In [63]:
# Take the Region data to another dataframe. Maybe one day it will be needed.

fbi_region = pd.concat([fbi_north[0:2], fbi_mid[0:2], fbi_south[0:2], fbi_west[0:2]])
fbi_region.reset_index(inplace=True, drop=True)
fbi_region

,Area,Year,Population,Violent crime,Murder and \nnonnegligent \nmanslaughter,Rape\n(revised definition),Rape\n(legacy definition),Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Region
0,Northeast,2015,56184737,180474,1967,16415,11912,56202,105890,951940,157910,737087,56943,Northeast
1,Northeast,2016,56209510,178244,1955,16651,12219,53033,106605,909897,142720,709721,57456,Northeast
2,Midwest,2015,67838387,242893,3422,30827,22395,62201,146443,1555516,307853,1125935,121728,Midwest
3,Midwest,2016,67941429,257109,3885,31408,23080,64022,157794,1544531,300359,1112596,131576,Midwest
4,South,2015,121039206,509043,7300,47277,33960,127149,327317,3393611,719098,2422679,251834,South
5,South,2016,122319574,526999,7961,49246,35869,128842,340950,3343799,684968,2391288,267543,South
6,West,2015,75834288,301773,3194,31615,22994,82557,184407,2123048,402703,1437787,282558,West
7,West,2016,76657000,320706,3449,33298,24562,86301,197658,2120808,387049,1424850,308909,West

In [64]:
# Clear first 2 rows of split data
fbi_north.drop(fbi_north.index[0:2], inplace=True)
fbi_north.reset_index(inplace=True, drop=True)
fbi_mid.drop(fbi_mid.index[0:2], inplace=True)
fbi_mid.reset_index(inplace=True, drop=True)
fbi_south.drop(fbi_south.index[0:2], inplace=True)
fbi_south.reset_index(inplace=True, drop=True)
fbi_west.drop(fbi_west.index[0:2], inplace=True)
fbi_west.reset_index(inplace=True, drop=True)

In [65]:
fbi_north['Geographic_Division'] = None
for i in range(fbi_north.shape[0]):
    if fbi_north['Area'][i][0:5] != '     ':
        fbi_north['Geographic_Division'][i] = fbi_north['Area'][i]

    else:
        fbi_north['Geographic_Division'][i] = fbi_north['Geographic_Division'][i-1]

# ----------------------------------------------------------------------------------

fbi_mid['Geographic_Division'] = None
for i in range(fbi_mid.shape[0]):
    if fbi_mid['Area'][i][0:5] != '     ':
        fbi_mid['Geographic_Division'][i] = fbi_mid['Area'][i]

    else:
        fbi_mid['Geographic_Division'][i] = fbi_mid['Geographic_Division'][i-1]

# -----------
fbi_south['Geographic_Division'] = None
for i in range(fbi_south.shape[0]):
    if fbi_south['Area'][i][0:5] != '     ':
        fbi_south['Geographic_Division'][i] = fbi_south['Area'][i]

    else:
        fbi_south['Geographic_Division'][i] = fbi_south['Geographic_Division'][i-1]

# ----------------------------------------------------------------------------------

fbi_west['Geographic_Division'] = None
for i in range(fbi_west.shape[0]):
    if fbi_west['Area'][i][0:5] != '     ':
        fbi_west['Geographic_Division'][i] = fbi_west['Area'][i]

    else:
        fbi_west['Geographic_Division'][i] = fbi_west['Geographic_Division'][i-1]

In [67]:
# Sample

fbi_south.head()

,Area,Year,Population,Violent crime,Murder and \nnonnegligent \nmanslaughter,Rape\n(revised definition),Rape\n(legacy definition),Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Region,Geographic_Division
0,South Atlantic,2015,63192408,256283,3824,21620,15433,66792,164047,1721061,352328,1246078,122655,South,South Atlantic
1,South Atlantic,2016,63923309,258672,4077,22333,16174,66402,165860,1692669,330122,1234761,127786,South,South Atlantic
2,Delaware,2015,944076,4760,62,361,257,1240,3097,25545,4797,19555,1193,South,South Atlantic
3,Delaware,2016,952065,4844,56,308,221,1359,3121,26334,5023,19791,1520,South,South Atlantic
4,District of Columbia,2015,670377,8538,162,494,365,3746,4136,31444,2971,25208,3265,South,South Atlantic

In [68]:
# Merge the split data

fbi = pd.concat([fbi_north, fbi_mid, fbi_south, fbi_west], ignore_index=True)

fbi['State'] = fbi['Area'].copy()
fbi.drop('Area', axis=1, inplace=True)
fbi.head()

,Year,Population,Violent crime,Murder and \nnonnegligent \nmanslaughter,Rape\n(revised definition),Rape\n(legacy definition),Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Region,Geographic_Division,State
0,2015,14710229,42121,326,4602,3374,9629,27564,257073,46260,193051,17762,Northeast,New England,New England
1,2016,14735525,41598,292,4505,3328,9407,27394,243769,42095,182985,18689,Northeast,New England,New England
2,2015,3584730,7938,116,798,585,2925,4099,65610,10286,48898,6426,Northeast,New England,Connecticut
3,2016,3576452,8123,78,763,561,2703,4579,64664,10045,47512,7107,Northeast,New England,Connecticut
4,2015,1329453,1726,23,461,337,311,931,24361,4694,18853,814,Northeast,New England,Maine

In [69]:
cols = ['Region', 'Geographic_Division', 'State']
cols += list(fbi.columns)
del cols[-3:]
cols
fbi = fbi[cols]
fbi.head()

,Region,Geographic_Division,State,Year,Population,Violent crime,Murder and \nnonnegligent \nmanslaughter,Rape\n(revised definition),Rape\n(legacy definition),Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft
0,Northeast,New England,New England,2015,14710229,42121,326,4602,3374,9629,27564,257073,46260,193051,17762
1,Northeast,New England,New England,2016,14735525,41598,292,4505,3328,9407,27394,243769,42095,182985,18689
2,Northeast,New England,Connecticut,2015,3584730,7938,116,798,585,2925,4099,65610,10286,48898,6426
3,Northeast,New England,Connecticut,2016,3576452,8123,78,763,561,2703,4579,64664,10045,47512,7107
4,Northeast,New England,Maine,2015,1329453,1726,23,461,337,311,931,24361,4694,18853,814

In [70]:

for i in range(fbi.shape[0]):
    if fbi['State'][i][0:5] == "     ":
        fbi['State'][i] = fbi['State'][i].replace("     ", "")

In [71]:
# Take the Division data to another dataframe. Maybe one day it will be needed like Region data.

fbi_division = fbi.loc[fbi['Geographic_Division'] == fbi['State']]

In [72]:
# Drop divisions from main dataframe

fbi.drop(fbi.loc[fbi['Geographic_Division'] == fbi['State']].index, inplace=True)
fbi.reset_index(inplace=True, drop=True)

In [73]:
# Update column names again

cols = list(fbi.columns)

for i in range(len(cols)):
    cols[i] = cols[i].replace("\n", "")

fbi.columns = cols

In [77]:
fbi.head(100)

,Region,Geographic_Division,State,Year,Population,Violent crime,Murder and nonnegligent manslaughter,Rape(revised definition),Rape(legacy definition),Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft
0,Northeast,New England,Connecticut,2015,3584730,7938,116,798,585,2925,4099,65610,10286,48898,6426
1,Northeast,New England,Connecticut,2016,3576452,8123,78,763,561,2703,4579,64664,10045,47512,7107
2,Northeast,New England,Maine,2015,1329453,1726,23,461,337,311,931,24361,4694,18853,814
3,Northeast,New England,Maine,2016,1331479,1648,20,412,300,266,950,21912,4003,17134,775
4,Northeast,New England,Massachusetts,2015,6784240,26453,131,2082,1538,5266,18974,114547,21826,84676,8045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,West,Pacific,California,2016,39250017,174796,1930,13702,10149,54789,104375,1002070,188304,637010,176756
96,West,Pacific,Hawaii,2015,1425157,3530,29,538,382,1085,1878,45389,6810,33140,5439
97,West,Pacific,Hawaii,2016,1428557,4417,35,619,447,994,2769,42753,6017,31082,5654
98,West,Pacific,Oregon,2015,4024634,10680,110,1650,1193,2163,6757,119752,18541,90514,10697
99,West,Pacific,Oregon,2016,4093465,10830,113,1721,1261,2278,6718,121345,16866,91286,13193

In [80]:
# from google.colab import files
# files.download("fbi.csv")
# Assuming your cleaned data is in a pandas DataFrame called 'fbi_clean'
fbi.to_csv('fbi_clean.csv', index=False)  # Save without index column

In [82]:
count_row = fbi.shape[0]
fbi.shape

(102, 15)